version: '3'

services:

  frontend:
    image: frontend:latest
    ports:
      - "8081:80"

  backend:
    image: github.com/akorshunov60-student/web:latest
    ports:
      - "8080"
    depends_on:
      - db
    command: bash -c "/apps/wait-for-service.sh db 3306 && /apps/entrypoint.sh"

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: